# We override the default clone step to workaround a bug with GitHub (see #3415)
clone:
  clone:
    image: plugins/git
    commands:
      - sleep 5s
      - git init
      - git remote add origin $DRONE_REMOTE_URL
      - git fetch --no-tags origin $DRONE_COMMIT_REF
      - if [ $DRONE_BUILD_EVENT = "push" ]; then git reset --hard -q $DRONE_COMMIT_SHA; else git checkout -qf FETCH_HEAD; fi
      - git submodule update --init --recursive

pipeline:
  test:
    group: test
    image: lampepfl/dotty:2018-01-17
    commands:
      - cp -R . /tmp/1/ && cd /tmp/1/
      - ./project/scripts/sbt "testOnly dotty.tools.dotc.CompilationTests dotty.tools.ShowClassTests"

  test_bootstrapped:
    group: test
    image: lampepfl/dotty:2018-01-17
    commands:
      - cp -R . /tmp/2/ && cd /tmp/2/
      - ./project/scripts/sbt "dotty-bootstrapped/testOnly dotty.tools.dotc.CompilationTests dotty.tools.ShowClassTests"

  test_optimised:
    group: test
    image: lampepfl/dotty:2017-11-17
    commands:
      - cp -R . /tmp/3/ && cd /tmp/3/
      - ./project/scripts/sbt "dotty-optimised/testOnly dotty.tools.dotc.CompilationTests dotty.tools.ShowClassTests"

branches:
  # The gh-pages branch holds the documentation and don't need to be built
  exclude: gh-pages
